FROM golang:1.17-alpine3.15
WORKDIR /app
COPY . .
RUN apk update && apk upgrade && apk add --no-cache git ca-certificates tzdata && update-ca-certificates
RUN go build -ldflags '-w -s -extldflags "-static"' -a -o application main.go

FROM scratch
COPY --from=0 /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
WORKDIR /app
COPY --from=0 /app ./
CMD ["./application"]